services:
  front-and-backend: 
    container_name: palm-and-vine-container
    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes: 
      - /app/node_modules
      - .:/app 
    ports:
      - "5173:5173" 
    #environment: #non mandatory environment settings
      # - DEBUG=1
      # - SECRET_KEY=
      # - ALLOWED_HOSTS=localhost,127.0.0.1 # host that will be allowed to connect
